### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'tilingScheme')

### ISSUE THREAD

**Issue by geographerwang** [lihanqiang/vue-vite-cesium-demo#8]
PS E:\project\github\vue-vite-cesium-demo-master> yarn run dev
yarn run v1.22.19
$ vite --mode development 

  vite v2.9.16 dev server running at:
  > Local:    http://localhost:9999/

  浏览器控制台打印如下消息，没有地图显示出来
[vite] connecting...
IonImageryProvider.js:175  Uncaught TypeError: Cannot read properties of undefined (reading 'tilingScheme')
    at IonImageryProvider.get (IonImageryProvider.js:175:36)
    at new Imagery (Imagery.js:38:55)
    at Imagery.createPlaceholder (Imagery.js:45:18)
    at new ImageryLayer (ImageryLayer.js:336:55)
    at ImageryLayerCollection.addImageryProvider (ImageryLayerCollection.js:147:17)
    at initCesium (initCesium.js:52:24)
    at Cesium.vue:391:16
client.ts:53 [vite] connected.
![QQ截图20231130191352](https://github.com/lihanqiang/vue-vite-cesium-demo/assets/12079968/64b2fc8f-7dad-4dc9-a008-0c32db4dbe4d)

**Comment by lihanqiang** [comment]
可以上传到codesandbox([](https://codesandbox.io/)) 上吗？应该是资源问题，或者你使用高德/百度/本地地图资源。

**Comment by lihanqiang** [comment]
[codesandbox](https://codesandbox.io/)

**Comment by lihanqiang** [comment]
或者在官网注册自己的资源。[https://ion.cesium.com/](https://ion.cesium.com/assets/)
![image](https://github.com/lihanqiang/vue-vite-cesium-demo/assets/16048224/820c5e4e-93f2-4927-a5c6-e0b18fa0bf80)

**Comment by lihanqiang** [comment]
请更新最新版本，重新依赖运行
